const allCaps = {
  caps: [
    {
      name: 'NIKE letter fashion trend Black cap',
      slug: 'cap-nike-letter-fashion-trend-black-cap',
      category: 'Caps',
      image: '/images/caps/cap1.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Gray/Black cap',
      slug: 'cap-nike-letter-fashion-trend-gray-black-cap#1',
      category: 'Caps',
      image: '/images/caps/cap2.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/White cap',
      slug: 'cap-nike-letter-fashion-trend-black-white-cap#1',
      category: 'Caps',
      image: '/images/caps/cap3.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Brown cap',
      slug: 'cap-nike-letter-fashion-trend-brown-cap',
      category: 'Caps',
      image: '/images/caps/cap4.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Blue cap',
      slug: 'cap-nike-letter-fashion-trend-blue-cap',
      category: 'Caps',
      image: '/images/caps/cap5.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/Red cap',
      slug: 'cap-nike-letter-fashion-trend-black-red-cap',
      category: 'Caps',
      image: '/images/caps/cap6.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/White cap',
      slug: 'cap-nike-letter-fashion-trend-black-white-cap#2',
      category: 'Caps',
      image: '/images/caps/cap7.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Clouded/Black cap',
      slug: 'cap-nike-letter-fashion-trend-clouded-black-cap',
      category: 'Caps',
      image: '/images/caps/cap8.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Gray/Black cap',
      slug: 'cap-nike-letter-fashion-trend-gray-black-cap#2',
      category: 'Caps',
      image: '/images/caps/cap9.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/White cap',
      slug: 'cap-nike-letter-fashion-trend-black-white-cap#3',
      category: 'Caps',
      image: '/images/caps/cap10.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default allCaps;
