import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'john@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'jane@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    // YEEZY SHOES
    //------------
    {
      name: "YEEZY BOOST 350 V2 'MX OAT'",
      slug: 'yeezy-boost-350-v2-mx-oat',
      category: 'Shoes',
      image: '/images/yeezy/shoe1.png',
      price: 179.99,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: "YEEZY BOOST 350 V2 'MX ROCK'",
      slug: 'yeezy-boost-350-v2-mx-rock',
      category: 'Shoes',
      image: '/images/yeezy/shoe2.png',
      price: 179.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 12,
      countInStock: 15,
      description: 'A popular shoes',
    },
    {
      name: "YEEZY BOOST 350 V2 'BELUGA'",
      slug: 'yeezy-boost-350-v2-beluga',
      category: 'Shoes',
      image: '/images/yeezy/shoe3.png',
      price: 149.99,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 13,
      countInStock: 24,
      description: 'A popular shirts',
    },
    {
      name: "ADIDAS YEEZY BOOST 700 V3 'CLAY BROWN'",
      slug: 'yeezy-boost-700-v3-clay-brown',
      category: 'Shoes',
      image: '/images/yeezy/shoe4.png',
      price: 279.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'MONO MIST'",
      slug: 'yeezy-boost-350-v2-mono-mist',
      category: 'Shoes',
      image: '/images/yeezy/shoe5.png',
      price: 214.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'MONO ICE'",
      slug: 'yeezy-boost-350-v2-mono-ice',
      category: 'Shoes',
      image: '/images/yeezy/shoe6.png',
      price: 214.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "ADIDAS YEEZY 700 V3 'ARZARETH'",
      slug: 'yeezy-700-v3-arzareth',
      category: 'Shoes',
      image: '/images/yeezy/shoe7.png',
      price: 279.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'CINDER NON-REFLECTIVE'",
      slug: 'yeezy-boost-350-v2-cinder-non-reflective',
      category: 'Shoes',
      image: '/images/yeezy/shoe8.png',
      price: 169.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 INFANTS 'SLATE'",
      slug: 'yeezy-boost-350-v2-infinite-slate',
      category: 'Shoes',
      image: '/images/yeezy/shoe9.png',
      price: 169.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 CMPCT 'SLATE RED'",
      slug: 'yeezy-boost-350-v2-cmpct-slate-red',
      category: 'Shoes',
      image: '/images/yeezy/shoe10.png',
      price: 209.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 700 V2 'TEPHRA'",
      slug: 'yeezy-boost-700-v2-tephra',
      category: 'Shoes',
      image: '/images/yeezy/shoe11.png',
      price: 199.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 700 'HI-RES RED'",
      slug: 'yeezy-boost-700-hi-res-red',
      category: 'Shoes',
      image: '/images/yeezy/shoe12.png',
      price: 189.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "ADIDAS YEEZY 700 V3 'FADE CARBON'",
      slug: 'yeezy-700-v3-fade-carbon',
      category: 'Shoes',
      image: '/images/yeezy/shoe13.png',
      price: 209.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'ADIDAS YEEZY BOOST 380 ALIENS',
      slug: 'yeezy-boost-380-aliens',
      category: 'Shoes',
      image: '/images/yeezy/shoe14.png',
      price: 249.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'DAZZLING BLUE'",
      slug: 'yeezy-boost-350-v2-dazzling-blue',
      category: 'Shoes',
      image: '/images/yeezy/shoe15.png',
      price: 159.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'MONO CLAY'",
      slug: 'yeezy-boost-350-v2-mono-clay',
      category: 'Shoes',
      image: '/images/yeezy/shoe16.png',
      price: 214.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "ADIDAS YEEZY 700 V3 'COOPER FADE'",
      slug: 'yeezy-700-v3-cooper-fade',
      category: 'Shoes',
      image: '/images/yeezy/shoe17.png',
      price: 199.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    //------------

    //T-SHIRTS
    //------------
    {
      name: 'Emporio Armani T–shirt (Black)',
      slug: 't-shirt-emporio-armani-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt1.png',
      price: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Emporio Armani T–shirt (Red)',
      slug: 't-shirt-emporio-armani-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt2.png',
      price: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt3.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt4.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-sh',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt5.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shi',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt6.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shir',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt7.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt8.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-c',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt9.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-cal',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt10.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvi',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt11.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt12.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-k',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt13.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-kle',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt14.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt15.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt16.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-po',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt17.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt18.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-b',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt19.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-bla',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt20.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt21.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black-',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt22.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black-wh',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt23.png',
      price: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default data;
