const allJerseys = {
  jerseys: [
    {
      name: '2022 World Cup Argentina Blue Jersey',
      slug: '2022-wc-argentina-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey1.png',
      oldPrice: 99.99,
      newPrice: 61.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Argentina White/Blue Jersey',
      slug: '2022-wc-argentina-white-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey2.png',
      oldPrice: 99.99,
      newPrice: 64.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Australia Yellow Jersey',
      slug: '2022-wc-australia-yellow-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey3.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Belgium Red',
      slug: '2022-wc-belgium-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey4.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Brazil Blue Jersey',
      slug: '2022-wc-brazil-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey5.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Brazil Yellow Jersey',
      slug: '2022-wc-brazil-yellow-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey6.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Croatia Blue/Light Blue Jersey',
      slug: '2022-wc-croatia-blue-light-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey7.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Croatia White/Red Jersey',
      slug: '2022-wc-croatia-white-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey8.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Morocco Red Jersey',
      slug: '2022-wc-morocco-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey9.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup France Blue Jersey',
      slug: '2022-wc-france-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey10.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Germany Red/Black Jersey',
      slug: '2022-wc-germany-red-black-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey11.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Germany White/Black Jersey',
      slug: '2022-wc-germany-white-black-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey12.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Japan Blue Jersey',
      slug: '2022-wc-japan-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey13.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Japan White Jersey',
      slug: '2022-wc-japan-white-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey14.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Morocco White Jersey',
      slug: '2022-wc-morocco-white-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey15.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Morocco Red Jersey',
      slug: '2022-wc-cup-morocco-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey16.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Netherlands Blue Jersey',
      slug: '2022-wc-netherland-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey17.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Netherlands Orange Jersey',
      slug: '2022-wc-netherlands-orange-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey18.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Portugal Red/Green Jersey',
      slug: '2022-wc-portugal-red-green-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey19.png',
      oldPrice: 99.99,
      newPrice: 64.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Portugal White/Green/Red Jersey',
      slug: '2022-wc-portugal-white-green-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey20.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Spain Blue Jersey',
      slug: '2022-wc-spain-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey21.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022',
      slug: '2022-',
      category: 'Jerseys',
      image: '/images/jerseys/jersey22.png',
      oldPrice: 99.99,
      newPrice: 61.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Spain Red Jersey',
      slug: '2022-wc-spain-red-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey23.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Uruguay White Jersey',
      slug: '2022-wc-uruguay-white-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey24.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Argentina Jersey 3 star (WORLD CUP 2022 CHAMPIONS EDITION)',
      slug: 'argentina-jersey-3-star',
      category: 'Jerseys',
      image: '/images/jerseys/jersey25.png',
      oldPrice: 99.99,
      newPrice: 79.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Bayern Away 22/23 Jersey',
      slug: 'bayern-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey26.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Bayern Home 22/23 Jersey',
      slug: 'bayern-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey27.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Borussia Dortmund Home 22/23 Jersey',
      slug: 'borussia-dortmund-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey28.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'RB Leipzig Home 22/23 Jersey',
      slug: 'rb-leipzig-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey29.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Atletico de Madrid Away 22/23 Jersey',
      slug: 'atletico-de-madrid-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey30.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Atletico de Madrid Home 22/23 Jersey',
      slug: 'atletico-de-madrid-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey31.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Barcelona Away 22/23 Jersey',
      slug: 'barcelona-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey32.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Barcelona Home 22/23 Jersey',
      slug: 'barcelona-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey33.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Real Madrid Away 22/23 Jersey',
      slug: 'real-madrid-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey34.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Real Madrid Home 22/23 Jersey',
      slug: 'real-madrid-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey35.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Marseille Home 22/23 Jersey',
      slug: 'marseille-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey36.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Monaco Home 22/23 Jersey',
      slug: 'monaco-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey37.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Kappa',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'PSG Away 22/23 Jersey',
      slug: 'psg-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey38.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Jordan',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'PSG Home 22/23 Jersey',
      slug: 'psg-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey39.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Atletico Mineiro Home 22/23 Jersey',
      slug: 'atletico-mineiro-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey40.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Le Coq Sportif',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Benfica Home 22/23 Jersey',
      slug: 'benfica-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey41.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Boca Juniors Home 22/23 Jersey',
      slug: 'boca-juniors-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey42.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Palmeiras Home 22/23 Jersey',
      slug: 'palmeiras-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey43.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Rangers Home 22/23 Jersey',
      slug: 'rangers-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey44.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Castore',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Sao Paulo Home 22/23 Jersey',
      slug: 'sao-paulo-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey45.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Sporting Home 22/23 Jersey',
      slug: 'sporting-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey46.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Vasco da Gama 22/23 Jersey',
      slug: 'vasco-da-gama-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey47.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Kappa',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Celtic Home 22/23 Jersey',
      slug: 'celtic-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey48.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Castore',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Corinthians Home 22/23 Jersey',
      slug: 'corinthians-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey49.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Flamengo Home 22/23 Jersey',
      slug: 'flamengo-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey50.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Fluminense Home 22/23 Jersey',
      slug: 'fluminense-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey51.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Umbro',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Galatasaray Home 22/23 Jersey',
      slug: 'galatasaray-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey52.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Gremio Home 22/23 Jersey',
      slug: 'gremio-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey53.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Umbro',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Liverpool Away 22/23 Jersey',
      slug: 'liverpool-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey55.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Liverpool Home 22/23 Jersey',
      slug: 'liverpool-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey56.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Manchester City Away 22/23 Jersey',
      slug: 'manchester-city-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey57.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Manchester United Away 22/23 Jersey',
      slug: 'manchester-united-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey59.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Manchester United Home 22/23 Jersey',
      slug: 'manchester-united-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey60.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Newcastle United Home 22/23 Jersey',
      slug: 'newcastle-united-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey61.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Castore',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Tottenham Hotspur Away 22/23 Jersey',
      slug: 'tottenham-hotspur-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey62.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Tottenham Hotspur Home 22/23 Jersey',
      slug: 'tottenham-hotspur-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey63.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'West Ham United Away 22/23 Jersey',
      slug: 'west-ham-united-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey64.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Umbro',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Juventus Away 22/23 Jersey',
      slug: 'juventus-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey65.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Juventus Home 22/23 Jersey',
      slug: 'juventus-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey66.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Inter Home 22/23 Jersey',
      slug: 'inter-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey67.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'AC Milan Away 22/23 Jersey',
      slug: 'ac-milan-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey68.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'AC Milan Home 22/23 Jersey',
      slug: 'ac-milan-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey69.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'AS Roma Home 22/23 Jersey',
      slug: 'as-roma-home-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey70.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'New Balance Official',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
  ],
};

export default allJerseys;
