const newProducts = {
  new: [
    {
      name: 'NIKE letter fashion trend Brown cap',
      slug: 'cap-nike-letter-fashion-trend-brown-cap',
      category: 'Caps',
      image: '/images/caps/cap4.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Blue cap',
      slug: 'cap-nike-letter-fashion-trend-blue-cap',
      category: 'Caps',
      image: '/images/caps/cap5.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Portugal Red/Green Jersey',
      slug: '2022-wc-portugal-red-green-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey19.png',
      oldPrice: 99.99,
      newPrice: 64.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Germany White/Black Jersey',
      slug: '2022-wc-germany-white-black-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey12.png',
      oldPrice: 99.99,
      newPrice: 69.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Manchester City Away 22/23 Jersey',
      slug: 'manchester-city-away-22/23-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey57.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Puma',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: "YEEZY BOOST 350 V2 'MONO MIST'",
      slug: 'yeezy-boost-350-v2-mono-mist',
      category: 'Shoes',
      image: '/images/shoes/shoe5.png',
      oldPrice: 249.99,
      newPrice: 214.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 CMPCT 'SLATE RED'",
      slug: 'yeezy-boost-350-v2-cmpct-slate-red',
      category: 'Shoes',
      image: '/images/shoes/shoe10.png',
      oldPrice: 229.99,
      newPrice: 209.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 700 'HI-RES RED'",
      slug: 'yeezy-boost-700-hi-res-red',
      category: 'Shoes',
      image: '/images/shoes/shoe12.png',
      oldPrice: 249.99,
      newPrice: 189.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'Nike Air Force 1 React',
      slug: 'nike-air-force-1-react',
      category: 'Shoes',
      image: '/images/shoes/shoe31.png',
      oldPrice: 159.99,
      newPrice: 119.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Nike Air Force 1 Low Utility 07 LV8',
      slug: 'nike-air-force-1-low-utility-07-lv8',
      category: 'Shoes',
      image: '/images/shoes/shoe33.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy T–Shirt (Black)',
      slug: 't-shirt-givenchy-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt9.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Blue)',
      slug: 't-shirt-kenzo-black-blue#2',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt20.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default newProducts;
