const allShirts = {
  tshirts: [
    {
      name: 'Emporio Armani T–shirt (Black)',
      slug: 't-shirt-emporio-armani-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt1.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Emporio Armani T–shirt (Red)',
      slug: 't-shirt-emporio-armani-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt2.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt3.png',
      oldPrice: 69.99,
      newPrice: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein T–Shirt (Black)',
      slug: 't-shirt-calvin-klein-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt4.png',
      oldPrice: 69.99,
      newPrice: 42.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein T–Shirt (Gray)',
      slug: 't-shirt-calvin-klein-gray',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt5.png',
      oldPrice: 69.99,
      newPrice: 42.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Fendi T–Shirt (Black) ',
      slug: 't-shirt-fendi-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt6.png',
      oldPrice: 409.99,
      newPrice: 349.99,
      brand: 'Fendi',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Fendi T–Shirt (White) ',
      slug: 't-shirt-fendi-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt7.png',
      oldPrice: 409.99,
      newPrice: 329.99,
      brand: 'Fendi',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (Black/White)',
      slug: 't-shirt-givenchy-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt8.png',
      oldPrice: 259.99,
      newPrice: 179.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy T–Shirt (Black)',
      slug: 't-shirt-givenchy-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt9.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy T-Shirt (Black/Brown)',
      slug: 't-shirt-givenchy-black-brown',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt10.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (Black)',
      slug: 't-shirt-givenchy-polo-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt11.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (White)',
      slug: 't-shirt-givenchy-polo-white#1',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt12.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (White)',
      slug: 't-shirt-givenchy-polo-white#2',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt13.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Blue)',
      slug: 't-shirt-kenzo-black-blue#1',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt14.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Black/Gold)',
      slug: 't-shirt-kenzo-black-gold',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt15.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Green)',
      slug: 't-shirt-kenzo-black-green',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt16.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Black/Red)',
      slug: 't-shirt-kenzo-black-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt17.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black)',
      slug: 't-shirt-kenzo-black',
      category: 'Kenzo',
      image: '/images/t-shirts/shirt18.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/White)',
      slug: 't-shirt-kenzo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt19.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Blue)',
      slug: 't-shirt-kenzo-black-blue#2',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt20.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Gray)',
      slug: 't-shirt-kenzo-gray#1',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt21.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Gray)',
      slug: 't-shirt-kenzo-gray#2',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt22.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Pink)',
      slug: 't-shirt-kenzo-pink',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt23.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default allShirts;
