const allLimited = {
  products: [
    {
      name: "YEEZY BOOST 350 V2 CMPCT 'SLATE RED'",
      slug: 'yeezy-boost-350-v2-cmpct-slate-red',
      category: 'Shoes',
      image: '/images/shoes/shoe10.png',
      oldPrice: 229.99,
      newPrice: 209.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'Kenzo T–Shirt (Black/White)',
      slug: 't-shirt-kenzo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt19.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: "YEEZY BOOST 350 V2 'MONO CLAY'",
      slug: 'yeezy-boost-350-v2-mono-clay',
      category: 'Shoes',
      image: '/images/shoes/shoe16.png',
      oldPrice: 259.99,
      newPrice: 214.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'Air Force 1 ’07 Low White Medium Blue',
      slug: 'air-force-1-07-low-white-medium-blue',
      category: 'Shoes',
      image: '/images/shoes/shoe32.png',
      oldPrice: 149.99,
      newPrice: 109.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Croatia Blue/Light Blue Jersey',
      slug: '2022-wc-croatia-blue-light-blue-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey7.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Givenchy T–Shirt (Black)',
      slug: 't-shirt-givenchy-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt9.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: "YEEZY BOOST 700 V2 'TEPHRA'",
      slug: 'yeezy-boost-700-v2-tephra',
      category: 'Shoes',
      image: '/images/shoes/shoe11.png',
      oldPrice: 249.99,
      newPrice: 199.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'Givenchy polo T–Shirt (White)',
      slug: 't-shirt-givenchy-polo-white-second',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt13.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default allLimited;
