const onSaleProducts = {
  onsale: [
    {
      name: 'NIKE letter fashion trend Black cap',
      slug: 'cap-nike-letter-fashion-trend-black-cap',
      category: 'Caps',
      image: '/images/caps/cap1.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Gray/Black cap',
      slug: 'cap-nike-letter-fashion-trend-gray-black-cap-second',
      category: 'Caps',
      image: '/images/caps/cap9.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/White cap',
      slug: 'cap-nike-letter-fashion-trend-black-white-cap-second',
      category: 'Caps',
      image: '/images/caps/cap7.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'NIKE letter fashion trend Black/Red cap',
      slug: 'cap-nike-letter-fashion-trend-black-red-cap',
      category: 'Caps',
      image: '/images/caps/cap6.png',
      oldPrice: 49.99,
      newPrice: 24.99,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 8,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Argentina Jersey 3 star (WORLD CUP 2022 CHAMPIONS EDITION)',
      slug: 'argentina-jersey-3-star',
      category: 'Jerseys',
      image: '/images/jerseys/jersey25.png',
      oldPrice: 99.99,
      newPrice: 79.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Bayern Home 22/23 Jersey',
      slug: 'bayern-home',
      category: 'Jerseys',
      image: '/images/jerseys/jersey27.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Portugal Red/Green Jersey',
      slug: '2022-wc-portugal-red-green-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey19.png',
      oldPrice: 99.99,
      newPrice: 64.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: '2022 World Cup Australia Yellow Jersey',
      slug: '2022-wc-australia-yellow-jersey',
      category: 'Jerseys',
      image: '/images/jerseys/jersey3.png',
      oldPrice: 99.99,
      newPrice: 54.99,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: 'Real Madrid Home 22/23 Jersey',
      slug: 'real-madrid-home',
      category: 'Jerseys',
      image: '/images/jerseys/jersey35.png',
      oldPrice: 99.99,
      newPrice: 59.99,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 12,
      countInStock: 20,
      description: 'Very good',
    },
    {
      name: "YEEZY BOOST 700 'HI-RES RED'",
      slug: 'yeezy-boost-700-hi-res-red',
      category: 'Shoes',
      image: '/images/shoes/shoe12.png',
      oldPrice: 249.99,
      newPrice: 189.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: "YEEZY BOOST 350 V2 'BELUGA'",
      slug: 'yeezy-boost-350-v2-beluga',
      category: 'Shoes',
      image: '/images/shoes/shoe3.png',
      oldPrice: 229.99,
      newPrice: 149.99,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 13,
      countInStock: 24,
      description: 'A popular shirts',
    },
    {
      name: 'Air Jordan 1 Retro High OG Heritage',
      slug: 'air-jordan-1-retro-high-og-heritage',
      category: 'Shoes',
      image: '/images/shoes/shoe18.png',
      oldPrice: 229.99,
      newPrice: 169.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Nike Air Force 1 Low ’07 All Black',
      slug: 'nike-air-force-1-low-07-all-black',
      category: 'Shoes',
      image: '/images/shoes/shoe25.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'FILA MARS gray/white',
      slug: 'fila-mars-gray-white',
      category: 'Shoes',
      image: '/images/shoes/shoe37.png',
      oldPrice: 149.99,
      newPrice: 119.99,
      brand: 'Fila',
      rating: 4.5,
      numReviews: 9,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: "ADIDAS YEEZY 700 V3 'COOPER FADE'",
      slug: 'yeezy-700-v3-cooper-fade',
      category: 'Shoes',
      image: '/images/shoes/shoe17.png',
      oldPrice: 229.99,
      newPrice: 199.99,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 3,
      countInStock: 14,
      description: 'A popular pants',
    },
    {
      name: 'Kenzo T-Shirt (Black/Red)',
      slug: 't-shirt-kenzo-black-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt17.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Emporio Armani T–shirt (Red)',
      slug: 't-shirt-emporio-armani-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt2.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (Black/White)',
      slug: 't-shirt-givenchy-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt8.png',
      oldPrice: 259.99,
      newPrice: 179.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
  ],
};

export default onSaleProducts;
