const allShirts = {
  tshirts: [
    {
      name: 'Emporio Armani T–shirt (Black)',
      slug: 't-shirt-emporio-armani-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt1.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Emporio Armani T–shirt (Red)',
      slug: 't-shirt-emporio-armani-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt2.png',
      oldPrice: 129.99,
      newPrice: 99.99,
      brand: 'Emporio Armani',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein polo T–Shirt (Black/White)',
      slug: 't-shirt-calvin-klein-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt3.png',
      oldPrice: 69.99,
      newPrice: 44.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein T–Shirt (Black)',
      slug: 't-shirt-calvin-klein-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt4.png',
      oldPrice: 69.99,
      newPrice: 42.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Calvin Klein T–Shirt (Gray)',
      slug: 't-shirt-calvin-klein-gray',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt5.png',
      oldPrice: 69.99,
      newPrice: 42.99,
      brand: 'Calvin Klein',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Fendi T–Shirt (Black) ',
      slug: 't-shirt-fendi-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt6.png',
      oldPrice: 409.99,
      newPrice: 349.99,
      brand: 'Fendi',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Fendi T–Shirt (White) ',
      slug: 't-shirt-fendi-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt7.png',
      oldPrice: 409.99,
      newPrice: 329.99,
      brand: 'Fendi',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (Black/White)',
      slug: 't-shirt-givenchy-polo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt8.png',
      oldPrice: 259.99,
      newPrice: 179.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy T–Shirt (Black)',
      slug: 't-shirt-givenchy-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt9.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy T-Shirt (Black/Brown)',
      slug: 't-shirt-givenchy-black-brown',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt10.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (Black)',
      slug: 't-shirt-givenchy-polo-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt11.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (White)',
      slug: 't-shirt-givenchy-polo-white-first',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt12.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Givenchy polo T–Shirt (White)',
      slug: 't-shirt-givenchy-polo-white-second',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt13.png',
      oldPrice: 279.99,
      newPrice: 199.99,
      brand: 'Givenchy',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Blue)',
      slug: 't-shirt-kenzo-black-blue-first',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt14.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Black/Gold)',
      slug: 't-shirt-kenzo-black-gold',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt15.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Green)',
      slug: 't-shirt-kenzo-black-green',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt16.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Black/Red)',
      slug: 't-shirt-kenzo-black-red',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt17.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black)',
      slug: 't-shirt-kenzo-black',
      category: 'Kenzo',
      image: '/images/t-shirts/shirt18.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/White)',
      slug: 't-shirt-kenzo-black-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt19.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Black/Blue)',
      slug: 't-shirt-kenzo-black-blue-second',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt20.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T-Shirt (Gray)',
      slug: 't-shirt-kenzo-gray-first',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt21.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Gray)',
      slug: 't-shirt-kenzo-gray-second',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt22.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Kenzo T–Shirt (Pink)',
      slug: 't-shirt-kenzo-pink',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt23.png',
      oldPrice: 179.99,
      newPrice: 119.99,
      brand: 'Kenzo',
      rating: 4.2,
      numReviews: 6,
      countInStock: 10,
      description: 'Very good',
    },
    {
      name: 'Fendi  T-shirt-Black',
      slug: 'fendi-t-shirt-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/shirt24.png',
      oldPrice: 699.99,
      newPrice: 299.99,
      brand: 'Fendi',
      rating: 4.9,
      numReviews: 12,
      countInstock: 24,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },
    {
      name: 'Fendi  T-shirt-White',
      slug: 'fendi-t-shirt-white',
      category: 'T-Shirts',
      image:
        '/images/t-shirts/FENDI Fashion Casual Summer Short sleeve T-shirt-White.png',
      oldPrice: 699.99,
      newPrice: 299.99,
      brand: 'Fendi',
      rating: 4.6,
      numReviews: 10,
      countInstock: 24,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },
    {
      name: 'Fendi polo shirt black',
      slug: 'fendi-polo-shirt-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/Fendi crna polo 2.png',
      oldPrice: 549.99,
      newPrice: 229.99,
      brand: 'Fendi',
      rating: 4.7,
      numReviews: 12,
      countInstock: 22,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },

    {
      name: 'Fendi polo shirt white',
      slug: 'fendi-polo-shirt-white ',
      category: 'T-Shirts ',
      image: '/images/t-shirts/Fendi bijela polo 2.png',
      oldPrice: 549.99,
      newPrice: 289.99,
      brand: 'Fendi',
      rating: 4.5,
      numReviews: 8,
      countInstock: 22,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },
    {
      name: 'Fendi summer polo shirt white',
      slug: 'fendi-summer-polo-shirt-white',
      category: 'T-Shirts',
      image: '/images/t-shirts/Fendi bijela polo 3.png',
      oldPrice: 799.99,
      newPrice: 309.99,
      brand: 'Fendi',
      rating: 4.9,
      numReviews: 11,
      countInstock: 25,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },

    {
      name: 'Fendi summer  polo shirt black',
      slug: 'fendi-summer-polo-shirt-black',
      category: 'T-Shirts',
      image: '/images/t-shirts/Fendi crna polo 3.png',
      oldPrice: 799.99,
      newPrice: 309.99,
      brand: 'Fendi',
      rating: 4.6,
      numReviews: 14,
      countInstock: 24,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },

    {
      name: 'Fendi white/gray  shirt',
      slug: 'fendi-white/gray-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Fendi bijela majica kratka.png',
      oldPrice: 849.99,
      newPrice: 349.99,
      brand: 'Fendi',
      rating: 4.4,
      numReviews: 9,
      countInstock: 12,
      description:
        'Fendi  is an Italian luxury fashion house producing fur, ready-to-wear, leather goods, shoes, fragrances, eyewear, timepieces and accessories. Founded in Rome in 1925, Fendi is known for its fur, fur accessories, and leather goods. Since 2001, Fendi has been part of the “Fashion & Leather Goods” division of French group LVMH.  Its headquarters are in Rome, in the Palazzo della Civiltà Italiana. ',
    },

    {
      name: 'Gucci black shirt',
      slug: 'gucci-black-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci crna majica.png',
      oldPrice: 390.99,
      newPrice: 259.99,
      brand: 'Gucci',
      rating: 4.9,
      numReviews: 11,
      countInstock: 13,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci polo black shirt',
      slug: 'gucci-polo-black-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci crna polo majica.png',
      oldPrice: 399.99,
      newPrice: 289.99,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 16,
      countInstock: 22,
      description:
        ' Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci polo white shirt',
      slug: 'gucci-polo-white-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci bijela polo majica.png',
      oldPrice: 399.99,
      newPrice: 289.99,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 16,
      countInstock: 22,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci summer white polo shirt',
      slug: 'gucci-summer-white-polo-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci summer white polo shirt.png',
      oldPrice: 420.99,
      newPrice: 299.99,
      brand: 'Gucci',
      rating: 4.9,
      numReviews: 8,
      countInstock: 24,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci 69 black shirt',
      slug: 'gucci-69-black-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci 69 black.png',
      oldPrice: 405.99,
      newPrice: 319.99,
      brand: 'Gucci',
      rating: 4.7,
      numReviews: 10,
      countInstock: 24,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },
    {
      name: 'Gucci 69 red shirt',
      slug: 'gucci-69-red-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci 69 red.png',
      oldPrice: 405.99,
      newPrice: 319.99,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 12,
      countInstock: 18,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci all black polo shirt',
      slug: 'gucci-all-black-polo-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci all black polo shirt.png',
      oldPrice: 444.99,
      newPrice: 309.99,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      countInstock: 23,
      description:
        ' Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci casual polo shirt (black)',
      slug: 'gucci-casual-polo-shirt-(black)',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci casual black polo shirt.png',
      oldPrice: 499.99,
      newPrice: 299.99,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 14,
      countInstock: 29,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },

    {
      name: 'Gucci casual polo shirt (white)',
      slug: 'gucci-casual-polo-shirt-(white)',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci casual white polo shirt.png',
      oldPrice: 499.99,
      newPrice: 299.99,
      brand: 'Gucci',
      rating: 4.9,
      numReviews: 18,
      countInstock: 22,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },
    {
      name: 'Gucci all white polo shirt',
      slug: 'gucci-all-white-polo-shirt',
      category: 'T-Shirts',
      image: '/images/t-shirts/Gucci all white polo shirt.png',
      oldPrice: 499.99,
      newPrice: 299.99,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      countInstock: 10,
      description:
        'Gucci is an Italian high-end luxury fashion house based in Florence, Italy.  Its product lines include handbags, ready-to-wear, footwear, accessories, and home decoration; and it licenses its name and branding to Coty, Inc. for fragrance and cosmetics under the name Gucci Beauty. In 2019, Gucci operated 487 stores for 17,157 employees, and generated €9.628 billion in sales (€8.2 billion in 2018). Marco Bizzarri is CEO of Gucci since December 2014, and Alessandro Michele was creative director from January 2015 to November 23, 2022. Gucci is a subsidiary of the French luxury group Kering. ',
    },
  ],
};

export default allShirts;
